name: ビルドする

on:
  workflow_call:
    inputs:
      upload-artifact:
        description: true の場合のみ、ビルド成果物を artifacts としてアップロードします。
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.114.1
    steps:
      - name: Hugo のインストール
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Dart Sass のインストール
        run: sudo snap install dart-sass

      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: ビルド
        env:
          HUGO_ENV: production
        run: hugo --gc --minify

      - name: ビルド成果物を artifacts としてアップロード
        if: ${{ inputs.upload-artifact == true }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
